name: テスト
description: テストです
title: "[request]: "
labels: ["contents-request"]
assignees:
  - littleIkawa
body:
  - type: markdown
    attributes:
      value: |
        マークダウンテスト
  - type: input
    id: in-test
    attributes:
      label: ラベルテスト
      description: 説明
      placeholder: プレースホルダ
    validations:
      required: true