name: 記事のリクエスト
description: 何か書いてほしいお題があれば投稿リクエストをお願いします（書くという保証はしません）。
title: "[request]: "
labels: ["contents-request"]
assignees: ["littleIkawa"]

body:
  - type: input
    id: request
    attributes:
      label: お題
    validations:
      required: true
  - type: textarea
    id: message
    attributes:
      label: 自由記述
      description: 含めてほしいトピックや追加情報など

